- README.md
Forgot to remove this after rewriting from scratch under CC0.
> Remove old etc attribution info

- .github/workflows/build.yaml
Forgot I added `openrpc.json` to `.gitignore` so it wasn't getting picked up in the deploy action.
> Manually perform push

- src/schemas/block.json
- src/schemas/transaction.json
An EIP-1559 signature is only valid on an EIP-1559 transaction, you cannot have a 1559 signature on a legacy transaction.  Because of this, I have broken things out so that there are separate concrete base types that then are specifically inherited by the signature types.  I also added rollup types for use in places like the TransactionInfo and TransactionWithSender.
I also renamed things so everything starts with `Transaction` and follows a fairly uniform naming scheme.  This will hopefully help with sorting and auto-complete tools.
Someone should double-check my work, I think I correctly set everything up, but a lot of copy/pasting happened and it is definitely possible I screwed something up.
> Transaction refactor.

- src/engine/interop/specification.md
The `engine_preparePayload` return type is changed from `payloadId|Error` to `Object|Error` for the sake of the future compatibility, i.e. this change allows for adding more data to the response of this method preserving backward compatibility.
> Engine API: make preparePayload return an object

- src/engine/README.md
- src/engine/specification.md
Create a "mainnet" copy of the engine specs to begin work on changes. Doing this in an isolated PR so subsequent feature change PRs are sane to review.
* copy over specification.md to `src/engine`. 
* note impending deprecation of interop engine spec in `src/engine/interop/specification.md` and in `src/engine/README.md`
> Create main version of specifiation.md for engineAPI

- src/engine/specification.md
*[Dependency on #81]*
Please review #81 before this as `src/engine/specification.md` was created there.
Once #81 is merged, I'll rebase and the diff here will just be 9cc2052
Remove `engine_consensusValidated` in accordance with it's removal from EIP 3675 (https://github.com/ethereum/EIPs/pull/4357) and the CL specs (https://github.com/ethereum/consensus-specs/pull/2660)
> Remove engine_consensusValidated

- src/engine/specification.md
- wordlist.txt
Defines a versioning mechanism for methods and structures and sets initial versions.
> Engine API: define versioning and set initial versions

- src/engine/specification.md
add `safeBlockHash` to `engine_forkchoiceUpdated`.
note that until a `safeBlockHash`  algorithm for CL is cleanly defined that CL will always submit `safeBlockHash = headBlockHash`.
Also note that this value is not critical to the consensus of EL but only to be utilized for user facing APIs
> add safeBlockHash to forkchoiceUpdated

- src/engine/specification.md
Adds `message` field to the response object of the `engine_executePayload` method.
Based on https://github.com/ethereum/execution-apis/pull/103
> Engine API: add message field to executePayload

- src/engine/specification.md
- Define `PAYLOAD_ID_VERSION_BYTE`: if we ever change the input types, but they happen to look the same when concatenated, the hash will be different.
- Move payload id computation to its own sub-section
- Fix previous typo in same line
Also, since the payload ID is `DATA`, not an integer, I see no reason to not just use a 32-byte identifier that is more resistant against collisions. **Can/should we change it to a 32 byte ID?**
If the actual intention is that collisions can happen, then we could change it to a `QUANTITY` and clarify that the engine-API user should check that the returned payload actually matches their original request (i.e. verify parent hash, timestamp, randomness attributes match expectation, and feeRecipient depending on trust).
> Version payload id computation and collision-resistant payload IDs

- src/engine/specification.md
- wordlist.txt
Refines `engine_forkchoiceUpdated` spec as per feedback by @MariusVanDerWijden:
* Adds and utilizes `ForkchoiceState` structure to be able to envelop the fork choice information in one argument. Proposed change regroups the parameter set of this method in a way that it has two subsets, `forkchoiceState` and `payloadAttributes`. Maintaining the parameter set of this method within two subsets does make sense since the semantics of `forkchoiceUpdated` method is twofold, and there is a parameter subset per each part of the semantics that can be updated independently.
* Adds `payloadId` to the response. It is natural if EL is responsible for the computation of build process identifiers as the process is initiated by EL. It also gets rid of the complexity related to maintaining the exact …
> Engine API: `engine_forkchoiceUpdated` refinement

- package.json
This PR updates the package.json links after the repository was renamed from `eth1.0-apis` to `execution-apis`
> Update package.json links

- package-lock.json
- src/eth/mining.json
- src/schemas/base-types.json
addresses #119 by correcting the parameters, based on https://github.com/ethereum/go-ethereum/blob/d8ff53dfb8a516f47db37dbc7fd7ad18a1e8a125/consensus/ethash/api.go#L66-L84
also addresses #106 by making the pattern for `uint` match `0x0`
> Fix eth_submitWork parameters, allow 0x0 uint

- src/engine/specification.md
This PR has the following renaming:
* `coinbase` to `feeRecipient`
* `feeRecipient` to `suggestedFeeRecipient`
cc @MicahZoltu
> Engine API: rename coinbase to feeRecipient

- src/engine/specification.md
Explicitly specifies that client software must respond with error if a PoW block referenced by  either `forkchoiceState.headBlockHash` or a parent of an execution payload does not satisfy terminal block conditions. The payload parent check maps on the corresponding check introduced in EIP-3675 by https://github.com/ethereum/EIPs/pull/4482
> Engine API: respond with error when terminal block conditions aren't satisfied

- src/engine/specification.md
Removes a port for WebSocket protocol as the same port can be used by both, HTTP and WebSocket, protocols (and others):
* https://localhost:8550
* wss://localhost:8550
cc @holiman @MicahZoltu
> Engine API: remove separate port for WebSocket protocol

- src/engine/specification.md
Refines the Message ordering section of the Engine API.
The previous version of the spec had the following overlooks:
* CL could flip two `forkchoiceUpdated` messages *before* the IDs were assigned which could result in inconsistency of the head of the chain between the layers
* The restrictions on EL side were too strong. EL couldn't process two different messages in parallel which e.g. locks the client until `executePayload` processing is finished
Proposed changes:
* CL: add the requirement to respect the order of occurrence of fork choice updated event
* EL: restrict enforcement of processing order to `forkchoiceUpdated` calls only
> Engine API: refine message ordering section

- src/engine/specification.md
Resolves https://github.com/ethereum/execution-apis/issues/120
> Engine API: inform CL with details on validation error

- src/engine/specification.md
Removes Message ordering mechanism based on request IDs. JSON-RPC request IDs might be difficult to get parsed depending on the JSON-RPC library. The new proposal doesn't rely on request IDs at all and removes the logic that is required to reset this ID, which in its turn introduces inconvenience for setups with multiple EL clients behind a load balancer.
The proposed approach doesn't require CL client software to send `forkchoiceUpdated` calls in a lock-step fashion. But it's based on the assumption that the underlying protocol doesn't mess up with the order of messages, i.e. if CL sends the following sequence of calls: `[fcU(A), fcU(B)]` then EL client will always receive `fcU(A)` before `fcU(B)`. This assumption gets broken if HTTP over multiple TCP sessions is used as the underlying …
> Engine API: Refine message ordering. Take 2

- scripts/build.js
This adds a new file to the assembled spec deploy `refs-openrpc.json` which lets other projects ref parts of it like [here](https://github.com/MetaMask/api-specs/blob/main/methods/eth_sendTransaction.json#L8).
fixes #70
> Add output of ref'd openrpc document for other consumers

- .gitignore
- scripts/build.js
This moves `writeFile` to before deref, looks like it mutates it.
> Fixed build where refs were still dereffed

- src/engine/specification.md
- wordlist.txt
The following changes to `executePayload` and `forkchoiceUpdated` methods are proposed:
* Makes execution semantics optional for `executePayload`, and renames this method to `newPayload` to make the name sound
* Adds an option to execute payload on receiving `forkchoiceUpdated` before updating the forkchoice state
* Allows for EL client to skip updating the forkchoice state if `forkchoiceUpdated` references a historical block from the canonical chain that has been validating a while ago, i.e. forkchoice state may never go backwards if an update to the same chain is requested
* Introduces `ACCEPTED` status. It may be sent in the response in the following cases:
* If CL sends a payload from a side fork and the parent block is missing, EL client software may just store this payload locally …
> Engine API: extend semantics of `executePayload` and `forkchoiceUpdated` methods

- src/engine/specification.md
Replaces `-32002: Invalid terminal block` error with `INVALID_TERMINAL_BLOCK` status value.
The motivation behind this change is to have terminal block conditions check handled in a way similar to other block validity conditions in terms of response to CL.
Additionally, this PR does also contain an explicit requirement on invalidating all descendants of the last PoW block in the chain if this PoW block is not a valid terminal block.
Alternatively, we could use an `INVALID` status to signal terminal block conditions violations. But this status is accompanied with `latestValidHash` which in the case of invalid terminal block can't be clearly defined, and moreover doesn't exist on CL. Thus, having a separate status tells that entire block tree starting from a transition block must be …
> Engine API: replace terminal block error with INVALID_TERMINAL_BLOCK status

- src/engine/specification.md
- wordlist.txt
Proposes to add `engine_getTransitionConfigurationV1` method
* Allows for EL heartbeat and for verifying that EL client distribution is configured correctly
* Gives ability for CL to ping EL constantly, match received configuration with its own and surface a problem to a user if misconfiguration occurs
This proposal introduces a method that is useful only before the merge transition with intention to deprecate it in a subsequent upgrade. Low implementation complexity should mitigate this downside.
> Engine API: add getTransitionConfiguration

- src/engine/authentication.md
- wordlist.txt
Follow-up to https://github.com/ethereum/execution-apis/issues/162 . 
Differences: 
- Added that we're using the 'next' port, 
- Added section about claims, and added two more optional claims. 
Todo: 
- examples
- reference the authentication.md from the main page
> Authentication for engine api

- src/engine/specification.md
Adds `latestValidHash` in the `forkchoiceUpdated` response when payload is deemed `INVALID`
> Engine API: fix forkchoiceUpdated INVALID response

- src/engine/specification.md
This is a very minor fix that clarifies that the `validationError` isn't *only* returned for an `INVALID` response.
> Clarify `validationError` usage

- src/engine/specification.md
The renaming relates to https://github.com/ethereum/consensus-specs/pull/2835 and https://github.com/ethereum/EIPs/pull/4836
> Engine API: random -> prevRandao

- src/engine/specification.md
This PR is based on the feedback received from CL client teams on a subset of `eth` methods their clients are relying on. The table with the list of methods can be found [here](https://hackmd.io/E9VKRcmRSc2Imo8RBtqxlw?view).
Additionally, it attempts to get rid of https://eth.wiki/json-rpc/API as a source of JSON-RPC spec and replace it with this repository. Though, eth.wiki is still used in one place as auxiliary resource.
Note `eth_chainId` isn't specified in [`eth`](https://github.com/ethereum/execution-apis/tree/main/src/eth) but is supported by all EL clients. Considering wide support of this method and state of Ethereum JSON-RPC Specification which is still in active development stage, including `eth_chainId` into this list seems to be fine.
> Engine API: define a subset of exposing eth methods

- src/engine/specification.md
This follows from a [Discord conversation](https://discord.com/channels/595666850260713488/692062809701482577/947845183414861826) about using the `engine_exchangeTransitionConfigurationV1` endpoint as a "ping" to allow an EL to be aware when it's CL is offline. (cc @djrtwo @mkalinin)
I imagine this to be particularly helpful in the space between:
1. Beacon chain Bellatrix fork
2. Terminal PoW block
During this period all ELs must be paired with a CL, but there's presently no way for them to know that the CL is connected and live.
> Add QoS for transition config endpoint

- src/engine/authentication.md
Slightly confused by this statement in the authentication spec. It appears the current state of the authentication spec (all legacy method should be provided) is contradicting the PR #183 (only a subset should be provided). Unless I misinterpret and the "legacy api" is the non-authenticated engine api? In which case believe the idea was to still remove that?
> Auth spec shouldn't specify which methods are provided over it

- src/engine/specification.md
Enforces the following validity condition before starting a build process: `payloadAttributes.timestamp > headBlock.timestamp`. If this condition isn't met responds with error but does not rolls back fork choice updated. Entire `forkchoiceUpdated` processing flow looks as follows after this change:
* Check `headBlock` is known and there is no missing data. If there are missing data respond with `SYNCING`
* Check `headBlock` is `VALID`. If it's not respond with `INVALID`
* Apply `forkchoiceState`
* Check `payloadAttributes.timestamp`. If it's invalid respond with error: `-32002: Invalid payload attributes`
* Start payload build process and respond with `VALID`
This might seem a bit ugly but this is a cost of double semantics of `forkchoiceUpdated` call. An alternative would be to check …
> Engine API: respond with error if payload attributes are invalid

- src/engine/specification.md
(supersedes #207)
* 8s timeout for engine endpoints **with** block execution semantics
* 1s timeout for engine endpoints **without** execution semantics
* provide directive that CL **MAY** call endpoints again that timeout (but they can also move on to other blocks [other chains or descendents).
Likely EL does not abort just because CL does, but EL can/should make the decision on how long to attempt to process (or attempt longer if called again).
> engine timeouts (redux)

- src/engine/specification.md
According to [JSON-RPC 2.0](https://www.jsonrpc.org/specification#error_object) spec, the range `[-32768; -32000]` is reserved for pre-defined errors. Applications should use values outside of this range.
This PR updates existing error codes. It might be a breaking change if a logic of any CL client relies on exact error code value (`-32001`).
> Engine API: adjust error codes with JSON-RPC 2.0 spec

- src/engine/specification.md
There could be the case (likely if CL is buggy) when `headBlock` does exist while either `finalizedBlock` or `safeBlock` does not.
This PR proposes to have an explicit check in `engine_forkchoiceUpdated` processing flow and the corresponding error message in response to the call if `forkchoiceState` is found inconsistent.
Should be rebased with https://github.com/ethereum/execution-apis/pull/211
> Engine API: return error if forkchoice state is inconsistent

- src/engine/specification.md
The spec does not adequately explain the difference between SYNCING and ACCEPTED for non-canonical branches.
For a block for a non-canonical branch to be ACCEPTED, it must be a "well-formed" chain of known ancestors.
Such a block with unknown ancestors cannot be ACCEPTED and must instead be signaled as SYNCING.
The purpose of ACCEPTED is to signal that there is in fact a well-formed chain but it has not yet been executed. ACCEPTED is not intended to also be for non-canonical branches missing requisite data.
> Clarify the difference between SYNCING and ACCEPTED

- src/engine/specification.md
Implements Option 3 from https://github.com/ethereum/execution-apis/issues/212, that is:
* Replace `INVALID_TERMINAL_BLOCK` status with `{status: INVALID, latestValidHash=0x00..00}` which simplifies the spec and CL implementations
* Fix a blind spot in the spec when merge transition block is itself `INVALID` by returning `{status: INVALID, latestValidHash=0x00..00}`
A list of places where according to this change EL must respond `{status: INVALID, latestValidHash=0x00..00}`:
* Replacement of `INVALID_TERMINAL_BLOCK`
* Invalid terminal PoW block is encountered during payload validation process
* Invalid terminal PoW is referenced by `headBlockHash` in `fcU` call
* New requirement
* Invalid *merge transition* block is encountered during payload validation process
This proposal does not …
> Engine API: replace INVALID_TERMINAL_BLOCK with INVALID + lvh=0x00..00

- graphql.json
Adds the consensus encoding of the following types to the graphql schema:
- `block`
- `block.header`
- `transaction`
- `transaction.receipt`
These fields can be computed on the client side so they're not strictly necessary. But having them as part of the schema makes debugging easier. It was first raised for receipts as part of https://github.com/ethereum/go-ethereum/issues/24720 and then extended to other types. Implementation in geth: https://github.com/ethereum/go-ethereum/pull/24816 and https://github.com/ethereum/go-ethereum/pull/24738
> graphql: add raw fields to block and tx

- .github/workflows/spellcheck.yaml
I have recently released 0.20.0 of the spellcheck GitHub action, I can see that you are using 0.16.0, so an update could be useful to you. Let me know if you have any issues with the proposal and I will try to accommodate.
I can recommend [Dependabot](https://github.com/dependabot) for keeping your GitHub actions up to date, if you want a PR proposing a basic configuration, please let me know.
> Bumped spellcheck GitHub action to version 0.20.0

- src/eth/block.json
- src/eth/transaction.json
- src/schemas/filter.json
Some APIs specified in older JSON-RPC documentation
accepted a block number or a block tag. Some carried
that difference over, some didn't.
This delta adds tags as an option to
* eth_getBlockByNumber
* eth_getBlockTransactionCountByNumber
* eth_getUncleCountByBlockNumber
* eth_getTransactionByBlockNumberAndIndex
This brings those APIs  in line with https://eth.wiki/json-rpc/API, 
except for eth_getLogs and eth_newFilter which have only 50% support for block tags among clients
Signed-off-by: Danno Ferrin <danno.ferrin@gmail.com>
> Change BlockNumber to BlockTags for existing APIs

- src/schemas/receipt.json
There is a schema disagreement over log.transactionHash between the ethereum execution apis and go-ethereum.
The ethereum execution apis do not mark that property as required https://github.com/ethereum/execution-apis/blob/main/src/schemas/receipt.json#L18-L21
The go-ethereum client however does mark that property as required https://github.com/ethereum/go-ethereum/blob/master/core/types/log.go#L45.
This PR marks log.transactionHash as required.
PS: there are more required properties missing (address, topics, data) but they are out of scope for this PR.
> log.transactionHash is required

- src/schemas/block.json
The original non-formal spec set the size of the block nonce to 8 bytes.
This PR updates the block nonce (and only the block nonce) to require an
8 byte value.
Signed-off-by: Danno Ferrin <danno.ferrin@gmail.com>
> Block nonce is 8 bytes

- src/engine/authentication.md
- wordlist.txt
Many lines had trailing whitespace and inconsistent capitalization of acronyms.
> require JWT keys to be exactly 32 bytes

- src/engine/specification.md
Considering the following EL block tree:
```
CA <- A1 <- A2 <- HEAD
\
<- B1 <- B2 <- B3  
```
Current spec allows to skip processing in following cases:
* `fcU(head: A2.blockHash)`, `fcU(head: A1.blockHash)` -- ancestors of the head of canonical chain
* `fcU(head: B2.blockHash)` -- ancestor of a tip of another chain (not a leaf)
After this change, the spec disallows to skip `fcU(head: B2.blockHash)`. For instance, when `BeaconBlock(B3)` appeared to be invalid but the `B3` itself is `VALID`, and then the network re-orgs to `BeaconBlock(B2)` the EL must handle such a re-org properly and start a build process if requested.
TODO:
Thanks to @rjl493456442 for helping to identify this issue.
H/t @djrtwo for the review
> Engine API: narrow down fcU skip conditions

- src/engine/specification.md
This change is proposed after the following situation occurred on MSF7:
* CL was syncing and sending an `fcU` to EL
* EL wasn't responding and CL timed out after 8s of waiting for the response
* An exact reason of why EL didn't respond doesn't matter, in this particular case EL started to sync and didn't respond with `SYNCING`
* CL didn't retry the call later on, thus, processing a beacon block stayed unfinished which bricked the sync process
* A node got stuck in a deadlock as CL stopped sending anything to EL because it was needed a signal from EL to proceed
CL could try to i) resend `fcU` ii) reprocess entire beacon block or do anything else to keep progressing in this scenario. These reactions are pretty much implementation specific. Therefore, the intention of proposed change is to …
> Engine API: recommend to retry the call after timeout

- src/engine/specification.md
Make explicit that when returning `INVALID` from payload validation, the child of the `latestValidHash`  in the invalid payload branch, is indeed `INVALID`, allowing thus the consumer to prune any block in this branch starting from said child.
> Make explicit that the child of LVH is INVALID

- src/engine/authentication.md
Clock drift can occur in resource constraint machines. During network issues both CLs and ELs resources tend to increase a lot, which can delay message processing and affect the JWT iat window. Having a "short" window of 5 seconds can escalate bad network condition into a full disconnect between CL and EL. If that happens the network stalls. Due to this DOS vectors could be cheaper since you only need to push one of the clients out of the 5s window.
@holiman is there any reasoning for the 5s value? Proposing to increase the value has:
**pros**:
- Higher resilience against broken comms between CL-EL during high resource usage
**cons**:
- ??
For this PR I picked 60s as a random value that's > 5s, but don't have any specific argument for it. Would like to hear opinions for
- 5s
- 20s
- 60s
- …
> Increase JWT issued-at window to 60s

- src/eth/client.yaml
It doesn't appear to be a standard method and I'm not clear what "version" it would be returning.
> Remove `eth_protocolVersion`

- .github/workflows/deploy.yaml
I made a modification to what `npm build` runs and forgot to update the CI deploy action. This should fix the error.
> Add stage to run `npm run build:docs`

- .github/workflows/deploy.yaml
- package.json
By running `npm run build:docs`, we overwrote the changes made with the preceding `sed` commands.
> Don't regenerate gatsby after changing config

- src/engine/specification.md
Allowing the successful exchange of the transition config values before the TTD is known allows users to setup their EL+CL *today*. This helps ensure the network is Ready For The Merge™ and helps with Testing The Merge™.
The consensus specs [specify a placeholder TTD](https://github.com/ethereum/consensus-specs/blob/c04f221fada2cf9bea33d05985fed8fcdcccde74/configs/mainnet.yaml#L16) of `115792089237316195423570985008687907853269984665640564039457584007913129638912`, which is equal to `2**256-2**10`. This value is absurdly high, but not the full size of a `uint256` such that we can still perform tests with greater-than-TTD values.
AFAIK, there is no equivalent placeholder value in the EL specs. Geth presently returns a TTD of `null` and Nethermind a value of `0`.
For reasons specified …
> Specify a placeholder TTD

- README.md
- docs/making-changes.md
- docs/testing.md
- tests/README.md
This PR adds some documentation around contributions to the specification. It specifically outlines the rough, informal process people usual follow when modifying the JSON-RPC and more concretely explains how to generate valid tests that can be consumed by the `rpc-compat` simulator. I am in parallel preparing some additional documentation in `rpc-compat`, so some of the references to "see the documentation in `rpc-compat`" currently fall flat.
PTAL and share any feedback!
> Contributor documentation

- tests/eth_gasPrice/get-current-gas-price.io
- tests/eth_maxPriorityFeePerGas/get-current-tip.io
These two methods are not deterministic across clients and have been failing on hive 2 for a while. I am going to remove them from the test suite, however, there is [hope](https://github.com/ethereum/hive/issues/640) to continue ensuring their correctness by making a few modifications to hive.
> eth: remove gasPrce and maxPriorityFee tests due to non-determinism

- src/engine/authentication.md
We should try to avoid using acronyms in specifications as it makes it harder for new participants in the ecosystem to process, so I have changed all references to EL and CL to execution layer and consensus layer.  Also, in many cases in this document the term EL was used when EL client was meant, so I appended "client" as appropriate.
While writing to the filesystem is useful in some setups, in others it may be a security risk.  For this reason, the **MUST** write to disk was changed to a **SHOULD** write to disk so that a client that doesn't write the token to disk isn't out of compliance.
> Adjusts wording and removes disk writing requirement.

- package-lock.json
- package.json
A regression was introduced in one of the graphql dependencies that cause CI to break. This PR makes it so we only accept patch updates to the listed versions.
> Hold dependency versions stable

- src/engine/blob-extension.md
- wordlist.txt
Updates the EIP-4844 spec extension to include withdrawals. The ExecutionPayloadV2 header is updated to do this. As with #197, this change isn't part of the core spec.
> Extend EIP-4844 to include withdrawals

- src/engine/shanghai.md
This is an initial draft for versioning `engine_getPayload` to support the EL client's estimate of the value of the block.  
This allows the CL to compare the value of locally built blocks to remotely build blocks received from relays/builders.
https://github.com/ethereum/execution-apis/issues/307
This PR is pending consensus on the optimal path to handle changes to the execution API.
Comments and/or improvements are welcome.
> Add engine_getPayloadV2 with locally built block value

- src/engine/experimental/blob-extension.md
We are missing timeout values for 4844 related calls.
- `engine_getPayloadV3`: 1s, easy to reason, same as previous versions
- `engine_getBlobsBundleV1`: 1s as a place holder, it does make some sense to align with `getPayload`. But after more testing, if we do realize this needs to be longer (hopefully not), we can adjust accordingly
> Add timeouts values to 4844 related methods

- .github/workflows/spellcheck.yaml
Hello
As the maintainer of the [spellcheck GitHub action](https://github.com/marketplace/actions/github-spellcheck-action) I am _sunsetting_ version 0.20.0 as by [sunset policy](https://github.com/rojopolis/spellcheck-github-actions/wiki#sunset-policy)
I have just released version 0.29.0, so this PR offers an update to the latest version.
Let me know if you have any issues with the proposed PR and I will try to accommodate.
I can recommend [Dependabot](https://github.com/dependabot) for keeping your GitHub actions up to date, alternatively there are [Renovate](https://github.com/marketplace/renovate), if you want a PR proposing a basic configuration for Dependabot, please let me know.
Happy new year
jonasbn
> Update of Spellcheck GitHub Action to version 0.29.0

- .github/workflows/test.yaml
- src/eth/state.yaml
- src/schemas/base-types.yaml
- src/schemas/receipt.yaml
- src/schemas/state.yaml
- tests/eth_getStorage/get-storage-invalid-key-too-large.io
- tests/eth_getStorage/get-storage-invalid-key.io
Fixes #303.
* There is an inconsistency with the base types where some types with a numeric post-fix value accept _only_ that quantity and other accept _up to_ that quantity. This PR makes it so all types accept _only_ that quantity (e.g. `Bytes32` requires exactly 32 bytes), with the exception of integers. They will continue to accept values _up to_ their quantity (e.g. `0x1` will match `uint256`).
* There is an error where `Bytes65` was copied from `Bytes512` and the bound was not updated. This has been resolved.
* There is an error with `uint256` where `0x` matched validly. It's been updated to follow the same pattern matching as other `uint` sizes, requiring no leading zeros.
* Some byte values actually have caps. I've added `BytesMax32` for use with storage keys. They don't quite …
> Increase strictness of base types

- src/engine/experimental/eip6110.md
Introduces Engine API specification of [EIP-6110](https://eips.ethereum.org/EIPS/eip-6110).
*Note:* Methods and structures modified by the EIP are versioned as `V6110`, while structures that are added by the EIP are versioned as `V1`. This is done to avoid potential clashes when several experimental features and hard forks are modifying the same structures and methods.
> Engine API: initial draft of EIP-6110 spec

- src/schemas/block.yaml
Reverts a change from #326 which turns block hashes into an object. I misunderstood this change and CI did not catch the issue in the tests.
> Revert block hash object

- src/engine/shanghai.md
This PR proposes the following cleanups to the Shanghai part of the spec:
* Sets timeouts whenever missed
* Makes validation of terminal PoW block conditions optional, so, client devs may remove it if they want
* Requires EL clients to stop using `INVALID_BLOCK_HASH` status and supplant it with `INVALID`, see https://github.com/ethereum/execution-apis/issues/270 for details (should be a one liner, if not let's debate)
If EL client implementations use the same piece of code for both `V1` and `V2` the latter two changes may become a problem as they seem to be backwards incompatible with `V1`. Though, practically it isn't that true as the transition has happened quite long time ago and having no TTD validation should not break anything except for Hive tests (though we should probably remove …
> Engine API: a bunch of cleanups

- src/engine/experimental/blob-extension.md
- src/engine/shanghai.md
This is how the spec is implied to work and how it already does work on many clients but it needs to be made explicit. Later versions of methods replace earlier versions and must return the appropriate object depending on the fork.
> Engine API: make engine_getPayloadVN fork agnostic

- src/schemas/state.yaml
Changed title of storage proof array to be plural. It was a bit confusing them being essentially the same name when one is an array.
> Changed storage proof array title to be plural

- src/engine/experimental/blob-extension.md
Use `BYTES_PER_FIELD_ELEMENT` instead of `size_of(BLSFieldElement)` as defined in: https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/polynomial-commitments.md#constants. I think the formal is more idiomatic?
> EIP4844: Use `BYTES_PER_FIELD_ELEMENT`

- src/engine/shanghai.md
Notes that syncing EL may not serve any block bodies even for blocks recently submitted via Engine API
> Syncing EL client may not serve block bodies

- src/engine/shanghai.md
Fixes edge cases when requested `count` is zero or `start` points to a genesis block.
Thanks to @siladu for bringing this up.
cc @arnetheduck
> Constrain ByRange parameter values

- src/engine/experimental/blob-extension.md
Syncing with https://github.com/ethereum/consensus-specs/pull/3218
> EIP4844: move excess data gas field to align with consensus spec

- src/engine/shanghai.md
Explicitly require CL clients to switch `newPayload` and `forkchoiceUpdated` to `V2` starting from Shanghai.
Summary of a problem: https://github.com/ethereum/hive/pull/706#issue-1574839378
Hive tests checking this requirement: https://github.com/ethereum/hive/pull/712
cc @marioevz
> Engine API: CL must switch to V2 methods since Shanghai

- src/engine/experimental/eip6110.md
Rename deposit fields using camel case for the sake of consistency with withdrawal
> Rename deposit fields

- src/engine/experimental/blob-extension.md
See #214, the error codes in Engine API changed mid last year, and we missed that change in the 4844 engine API draft.
Credits to FLCL (discord) for finding this inconsistency.
Since it's only an error code, I think it's safe to roll this out to 4844 devnets without special coordination. I'll add this change to the 4844 call agenda so nobody misses it.
> eip-4844: update Unknown Payload error code to match latest Engine API spec

- src/engine/experimental/blob-extension.md
In reference to the PR: https://github.com/ethereum/EIPs/pull/6610, EL can now just return proofs in `engine_getBlobsBundleV1` which can be easily validated into CL using `verify_blob_kzg_proof_batch` and used to build individual blobSideCar
> Add corresponding proofs to BlobsBundleV1

- src/engine/paris.md
Adds a statement that `payloadId` value returned EL client software should be different for two distinct `PayloadAttributes` objects
> State that `payloadId` should be unique for each `PayloadAttributes` instance

- src/engine/experimental/blob-extension.md
As per decision made on [EIP-4844 Implementers' Call #20](https://github.com/ethereum/pm/issues/755) adds `blobsBundle` field to the `getPayloadV3` response getting rid of `blockHash` field in `BlobsBundleV1` data type and statements enforcing consistency between `getPayloadV3` and corresponding `getBlobsBundleV1` calls.
> Merge `getPayloadV3` and `getBlobsBundleV1`

- graphql.json
- schema.graphqls
**TL;DR** After this PR every number field will be hex-formatted. Numeric inputs are flexible and can be provided as number or string.
The spec is vague in defining which inputs are accepted for `Long` and how outputs are formatted. I suggest that `Long` behave similar to `BigInt`s in this sense. I.e. be flexible when taking input, but output hex-encoded values. My reasoning is that:
- JSON-RPC API returns all the long values as hex.
- Even though BigInt is a thing in JS-land, parsing a big uint64 literal in JS will still be inaccurate. Case in point this happens also in the GraphiQL UI which both Besu and Geth use this issue exists. There's a [proposal](https://github.com/tc39/proposal-json-parse-with-source) which will help with this however it is not accepted for being included into …
> graphql: specify Long input and output formats

- src/engine/experimental/blob-extension.md
Adds blob versioned hashes as a second parameter to `engine_newPayloadV3` as a follow up to https://github.com/ethereum/consensus-specs/pull/3345#issuecomment-1547327209
> Engine API: validate blob versioned hashes

- graphql.json
- schema.graphqls
Geth implementation: https://github.com/ethereum/go-ethereum/pull/27072
Hive tests: https://github.com/ethereum/hive/pull/764
> graphql: add withdrawals (EIP-4895)

- src/engine/experimental/blob-extension.md
Aligning Deneb blob spec on these two things:
- Add `data_gas_used` field to `ExecutionPayload` https://github.com/ethereum/consensus-specs/pull/3391
- Change `ExecutionPayload.excess_data_gas` type from `uint256` to `uint64` https://github.com/ethereum/consensus-specs/pull/3392
> Update `PayloadV3` with data gas used

- src/engine/experimental/blob-extension.md
UPDATE:
This PR proposed two things
i. Arrays are of the same length.
ii. The length is limited by MAX_BLOBS_PER_BLOCK .
Consensus to keep (i) and let CL handle (ii) in process block ops (where the MAX_BLOBS_PER_BLOCK check has already been placed)
-------------------------------------
In consensus specs, the blob limit it can handle is defined by `MAX_BLOBS_PER_BLOCK` and this check in apis will make the EL aware of this limit in CL and have mitigations (like perform min(MAX_DATA_GAS_PER_BLOCK / DATA_GAS_PER_BLOB,MAX_BLOBS_PER_BLOCK) to get  actual blob limit for the block to return in execution apis
> Assert array items in BlobsBundleV1 to be of same length

- src/engine/common.md
- src/engine/experimental/blob-extension.md
This change switched `V3` methods to one method - one structure approach that we have agreed upon in the recent ACDC.
This PR enforces EL client to check that parameters and their fields in `newPayloadV3` aren't `null` and makes the client to respond with error otherwise. Also, a similar validation is applied to the `timestamp` being greater or equal to 4844 activation. This enforcement can protect us from bugs like when CL attempts to send an old payload structure and EL accepts it. Happy to hear more inputs on that.
EDIT: A new `-38005: Unsupported fork` error is introduced to surface the case when a payload is from a fork that is not supported by a method e.g. Shanghai payload is submitted via `newPayloadV3` which minimal supported fork is Cancun.
> Engine API: employ one method one structure approach for V3

- src/engine/experimental/eip6110.md
* adjusts `ExecutionPayloadV6110`  with `ExecutionPayloadV3`
* adds `newPayloadV6110` and `getPayloadV6110` methods instead of modified `V2` methods
> Rebase eip6110 to Cancun

- scripts/build.js
The methods that appear in the published docs are not sorted by method name. This may not matter when looking for a particular method (as you can use Ctrl-F/Cmd-F in your browser), but not so when using the list as a whole. In our case, we have a proxy to Ethereum in our project, and we want to ensure we have proper test coverage for all public Ethereum RPC methods. This is difficult when the official list of methods is unsorted because we have to double- and triple-check that we've accounted for all of them on our side. If the list were sorted then this task would be a lot easier.
---
I tried my best to build the docs locally but ran into an error while doing so, so I hope this produces the correct result. Let me know if there's anything I need to do to prove that this works.
> Sort RPC methods in docs

- src/schemas/base-types.yaml
65 bytes is represented as a 130 character hex, not 65 characters.
Before:
After:
> fix: incorrect hex EIP-191 regex length

- src/engine/cancun.md
- src/engine/openrpc/methods/payload.yaml
Successor of https://github.com/ethereum/execution-apis/pull/395 suggesting to scope `shouldOverrideBuilder` flag for Cancun.
> Scope shouldOverrideBuilder flag for Cancun

- src/eth/transaction.yaml
- Sets the transaction hash param as required in the docs because it was shown as optional
Before:
After:
> define tx hash paramter as required for  eth_getTransactionReceipt

- src/schemas/transaction.yaml
fixes #80 
Before the spec moved to this repository, we agreed to include `gasPrice` for EIP-1559 txs as a deprecated field to aid in the transition for tooling. I believe most clients have implemented it this way. Geth has [here](https://github.com/ethereum/go-ethereum/blob/d4d88f9bce13ca9310bf28f5f26ea9f1915ba90d/internal/ethapi/api.go#L1422-L1428).
> eth: add gas price field to 1559 txs

- src/schemas/transaction.yaml
It looks like many clients are currently either not returning `yParity` or returning both `v` and `yParity`. To align the spec with this, I'm proposing we add an optional (but deprected) `v` value for 2930 and 1559 txs. This way clients can continue use it and tooling can have some space to upgrade to `yParity`.
> eth: add optional v value for 2930 and 1559 txs

- src/schemas/transaction.yaml
Oversight in #444. Should have included `uint` pattern ref.
> eth: fix, add pattern to 1559 gas price

- src/schemas/block.yaml
> Add Parent Beacon Block Root to Block

- src/eth/submit.yaml
- src/schemas/receipt.yaml
- src/schemas/transaction.yaml
As discussed in recent 4844 implementers calls, this proposes to add optional fields for `blobGasUsed` and `blobGasPrice` to the transaction receipt object specific to 4844 blob transactions.
> Add EIP-4844 transaction and receipt

- src/engine/paris.md
Clarifies EL’s behaviour in the following case mentioned by @potuz:
1) NewPayload 6 -> SYNCING
2) FCU 6 -> INVALID, LVH:5
Some CL MAY send FCU: 5 in this case. Edit: Prysm will send here in most cases too
EL must update its forkchoice state when FCU: 5 is sent.
The skip was originally introduced to handle a scenario when CL is syncing from scratch while EL was fully synced up to some moment in the past. This fix is related to the online mode when a node is fully sync and doesn’t affect the original scenario.
cc @marioevz it would be great to have a test covering this scenario some time after the PR gets merged
> engine: skip fcU only when the ancestor of the canonical head is VALID

- src/engine/paris.md
This essentially copies over https://github.com/ethereum/consensus-specs/blob/v1.4.0-beta.4/sync/optimistic.md#transitioning-from-valid---invalidated-or-invalidated---valid into more execution-layer specs.
The current specs don't use a verb much to describe the specific process of determination of `VALID`, et cetera, but more the whole response construction. The one time I could find they unambiguously do, that verb is "classify", so went with that.
The intent here is to disallow this equivocation even over time, i.e. for any given `newPayload` or fcU, by construction it can't equivocate, and simply being incorrect indefinitely is not great either, but then that EL is just broken, in more significant ways.
The harm/fallout/externality that's resulting from this is exactly that for …
> disallow `VALID` <-> `INVALID` equivocation

- src/engine/cancun.md
- src/engine/paris.md
This PR incorporates changes proposed by https://github.com/ethereum/execution-apis/pull/476, https://github.com/ethereum/execution-apis/pull/479 and results from the conversations happening in-person during the DevConnect and in the Discord after the event.
The list of proposed changes:
1. Update fcu v1 spec to explicitly state that `payloadAttributes` validations and build process can only be run after `forkchoiceState` is processed and only if the `head` is `VALID` implying that if a client is `SYNCING` no `payloadAttributes` validations are run.
2. State that `forkchoiceState` fields must be validated before any processing starts with the corresponding error on failure.
3. Define a new sequence of `payloadAttributes` checks that must be run *after applying the fork choice state*.
The …
> engine: clarify `payloadAttributes` checks and fcu v3 processing flow

- src/engine/common.md
- src/engine/identification.md
- wordlist.txt
By analyzing the structure of beacon blocks on the network, we are able to obtain [fairly accurate data](https://blockprint.sigp.io/) on consensus layer client diversity. Unfortunately, do to the fact that the **overwhelming majority** of validators use `mev-boost`, their execution clients do not leave *any* fingerprint behind in block proposals. Thus we are forced to rely on limited [self-reporting](https://execution-diversity.info/) data from staking pools. Many pools do not participate, and we often have outdated statistics for the pools that do. Worse yet, we have **no** data on client diversity for home stakers.
This PR can change that by allowing consensus clients to learn which execution client they are connected with.
Consensus clients can then embed this in their `graffiti` field …
> Specify Client Versions on Engine API

- src/engine/openrpc/schemas/payload.yaml
- src/engine/prague.md
Since EIP-7251 is included into Pectra fork. We should consider including it in the Engine API spec.
One of the features of EIP-7251 is to integrate EIP-7002 to support execution layer triggerable **partial** withdrawals via `ExitV1`.
This PR adds `amount` to `ExitV1` such that it supports partial withdrawals on top of full exits.
A point of discussion is the use of word `exit`. Originally EIP-7002 only considers full withdrawals (exits). With the newly added responsibility, one may consider renaming `exit` to `executionLayerWithdraw` for more precise description and to be distinguishable from the current withdrawal mechanism (consensus layer triggered).
> Add EIP-7251 to Prague

- src/engine/openrpc/schemas/payload.yaml
- src/engine/prague.md
This PR makes good on some pending changes to 6110 and 7002. It was discussed a roughly accepted in [CL call 132](https://github.com/ethereum/pm/issues/1010).
These three in particular:
* https://github.com/ethereum/EIPs/pull/8440
* https://github.com/ethereum/EIPs/pull/8406
* https://github.com/ethereum/EIPs/pull/8469
The result is `DepositReceiptV1` -> `DepositRequestV1` and `ExitV1` -> `WithdrawalRequestV1`.
> engine: rename for 7002 partial withdrawals and 7685 requests

- src/schemas/base-types.yaml
im using this schema and json schema faker and this address schema pattern generates addresses with commas in them:
also removed them from `byte` while I was in there
> remove comma from base types pattern

- src/engine/openrpc/methods/payload.yaml
- src/engine/openrpc/schemas/payload.yaml
- src/engine/prague.md
Introduces `ExecutionPayloadBodyV2` to accommodate `depositRequests` and `withdrawalRequests` added to the payload body in Prague, this entails adding new `engine_getPayloadBodiesByRangeV2` and `engine_getPayloadBodiesByHashV2` methods. This PR also contains a few naming adjustments in the examples part of the schema.
> engine: Extend payload bodies with deposit and withdrawal requests

- src/engine/openrpc/methods/payload.yaml
- src/engine/openrpc/schemas/payload.yaml
- src/engine/prague.md
There is an inconsistency between the withdrawal request defined in EIP-7002 (see [validator_pubkey field](https://eips.ethereum.org/EIPS/eip-7002#validator_pubkey-field) and [related PR](https://github.com/ethereum/execution-specs/pull/950/files#diff-77ebf5e20ee4c5146610db95299dba8a605609386fcb37f12d9d2aa3d95dfed3R162)), the consensus spec (see [ExecutionLayerWithdrawalRequest](https://github.com/ethereum/consensus-specs/blob/d29581315579d37064abf21b174750f9d5c099c0/specs/electra/beacon-chain.md?plain=1#L237)), and the execution api.
This PR align the execution api spec WithdrawalRequestV1 with the other specs.
Most ELs currently return it as `validatorPublicKey` with the exception of Besu which uses `validatorPubKey`
> engine: align WithdrawalRequestV1 with EIP-7002 and consensus spec

- src/engine/common.md
- src/engine/paris.md
- src/engine/prague.md
- src/engine/shanghai.md
> Fix: typos

- src/engine/prague.md
Tiny pedantic change to ensure consistency between response structures and their textual descriptions when it comes to `consolidationRequests`.
> engine: mention `consolidationRequests` in API descriptions

- src/engine/identification.md
Hi all :wave: https://github.com/ethereum/trin/tree/master/trin-execution
We are building an execution client with the initial goal of bridging data into the Portal Networks, without devp2p. So I thought I would make a PR to reserve our own code (which is mentioned in the `identification.md` document.
For context about the `without devp2p` part, a longer term goal would be to build it out so it rely's on the Portal Network instead, for transaction gossip and access to old history/state. Currently we can get everything we need to sync to latest from `.era`/`.era1` files and the consensus client itself. Which bypasses the use of devp2p for now, but of course we still need access to the consensus layer through the engine api.
> engine: specify Trin Execution ClientCode

- src/engine/prague.md
This is to mirror [a change in EIP-7685](https://github.com/ethereum/EIPs/pull/8989), where we exclude requests with empty request_data from the commitment.
> engine: exclude empty requests in requests list

- src/engine/paris.md
As part of `newPayload` block hash verification, the `transactionsRoot` is computed by the EL. Because Merkle-Patricia Tries cannot contain `[]` entries, MPT implementations typically treat setting a key to `[]` as deleting the entry for the key. This means that if a CL receives a block with `transactions` containing one or more zero-length transactions, that such transactions will effectively be skipped when computing the `transactionsRoot`. Note that `transactions` are opaque to the CL and zero-length transactions are not filtered out before `newPayload`.
```python
def compute_trie_root_from_indexed_data(data):
"""
Computes the root hash of `patriciaTrie(rlp(Index) => Data)` for a data array.
"""
t = HexaryTrie(db={})
for i, obj in enumerate(data):
k = encode(i, big_endian_int)
t.set(k, …
```
> Synchronously check all `transactions` to have non-zero length

- src/eth/block.yaml
- src/schemas/block.yaml
eth_ RPC counterpart to https://github.com/ethereum/execution-apis/pull/574
> EIP-7742 - Add target_blobs_per_block to Block schema

- src/eth/state.yaml
- src/schemas/base-types.yaml
Closes #556.
The issue with the suggested update to the regex `^0x([1-9a-f][0-9a-f]{0,63})|0$` was that it allowed `0xanything0` to be valid. This issue also exists in the current implementation, which is why the test "works fine," as @fvictorio mentioned. My updated regex addresses all the problems mentioned in the issue and fixes the `|0` edge case.
**My proposed regex:**
```
^0x(([1-9a-f][0-9a-f]{0,63})|0{1,64})$
```
> fix incorrect regular expressions for uint base types

- src/eth/state.yaml
this ends up giving an error `hex string invalid`
> remove invalid hex from getProof storageKeys example

- graphql.json
- schema.graphqls
PR to geth: https://github.com/ethereum/go-ethereum/pull/27963
> graphql: add fields for eip-4844

- src/schemas/receipt.yaml
- src/schemas/transaction.yaml
Motivation
This is  for closing #561
As mentioned I have added same eip 1559 + auth list referenced to reciept schema where added authlist definition
> add EIP-7702 transactions and receipts

- src/engine/prague.md
Adds an explicit Engine API error code in case the requests contain an invalid request (out of order, empty or contains only type byte).
> Explicit error code in `engine_newPayloadV4` for Prague

- src/engine/prague.md
Adds another explicit scenario where `engine_newPayloadV4` should return `-32602: Invalid params`.
For example, in the following requests list, the request elements are technically not out of order, and they have a length of more than one byte, but should still be considered invalid:
```
[
"0x02a94f5374fce5edbc8e2a8697c15331677e6ebf0b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001",
"0x02a94f5374fce5edbc8e2a8697c15331677e6ebf0b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001"
]
```
> Add failure type for duplicate requests

- src/engine/prague.md
https://github.com/ethereum/execution-apis/pull/623 clarified some error conditions for `executionRequests` in the `engine_newPayloadV4 ` request. 
This PR replicates the same conditions for `engine_getPayloadV4` to keep things consistent.
> Clarify error conditions for getPayload

- src/engine/prague.md
Extends `engine_forkchoiceUpdatedV3` usage for Prague
Credits to @siladu
> engine: Modify fcuV3 to handle payload building in Prague

- src/engine/cancun.md
All the EL clients from the [Pectra Testnet announcement](https://blog.ethereum.org/2025/02/14/pectra-testnet-announcements), [except Erigon](https://github.com/erigontech/erigon/issues/12284) which seems to have indicated support for doing so, support `engine_getBlobsV1` already, so this PR recognizes and ratifies this status quo.
`engine_exchangeCapabilities` in general doesn't suffice because of [TOCTOU](https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use) concerns around swapping out of ELs at specified endpoints at arbitrary times, plus nuanced and unpredictable interactions with EL/JSON-RPC multiplexers, mean that at best, such capability-probing is still a best-effort gamble.
Various advocacy for increased blob count explicitly assumes `engine_getBlobsV1` will exist to …
> make engine_getBlobsV1 non-optional as of Pectra

- src/eth/execute.yaml
- src/schemas/block.yaml
- src/schemas/execute.yaml
- src/schemas/transaction.yaml
- tests/eth_simulateV1/ethSimulate-empty-ethSimulate.io
Fixes the issues that was causing CI to break. I see there are still some more issues in the same vein of what was fixed (particularly around the constant error codes), but will probably resolve those in a separate PR.
> Fix invalid eth_simulate schema

- src/schemas/execute.yaml
Instead of redefining logs object in eth_simulateV1's spec, use the generic log object
> Change eth_simulateV1 to use generic log object

- src/eth/filter.yaml
- Filters do not register for notifications
- filter IDs are required for many methods
- the log filter object is required for the newFilter method
- getFilterChanges returns an array of things depending on the filter
I do not know what getFilterLogs does, but the spec is identical to filter changes, so i suspect either
- the spec is in error here and it returns only logs
- the description is in error, and the name is misleading, and it may return block or tx hashes
> eth: improve filter API spec
