ethereum/execution-apis

openrpc.json
=> Add eth_getTransactionReceipt

.github/workflows/build.yaml, .github/workflows/deploy.yaml
=> Fix deployer

.github/workflows/build.yaml
Apparently this should be done before pushing.
=> Configure git user

.github/workflows/build.yaml
=> Create depoy branch before push

scripts/build.js, src/methods/block.json, src/schemas/block.json
=> Fix block getters

README.md
=> Update View the spec link in README

package-lock.json, package.json, scripts/build.js
Since `allOf` doesn't _quite_ have the properties we're looking for, we can use an external library to merge the schemas during the build process.
=> Merge instances of `allOf`

.github/workflows/deploy.yaml, .github/workflows/test.yaml
=> Ensure deploy workflow installs relevant pkgs

src/engine/interop/specification.md
Fixes error messages in the spec
=> Engine API: fix grammar and error messages

src/engine/specification.md
Supersedes https://github.com/ethereum/execution-apis/pull/79
=> Engine API: add toc

src/eth/state.json
Fixed spelling error referenced in Issue #95
=> Added "At" to eth_getStorageAt

src/engine/specification.md
s/lastestValidHash/latestValidHash
=> Fix `engine_executePayloadV1` typos

src/schemas/receipt.json
=> Add missing properties to `ReceiptInfo` schema

src/engine/specification.md
Incorporates feedback from #131
=> Rename receiptRoot to receiptsRoot in execution payload

src/engine/specification.md
link to consensus-specs was broken after merge->bellatrix renaming
=> fix broken merge link

src/eth/client.json
=> eth: add eth_chainId method

package-lock.json
Updates some outdated dependencies.
=> all: update vulnerable deps

README.md, src/engine/specification.md
=> Get rid of eth1.0 leftovers

src/eth/execute.json, src/eth/state.json
closes #98, closes #99, closes #112
=> add BlockNumberOrTag to eth_call, eth_estimateGas

src/eth/fee_market.json
=> add eth_feeHistory summary, description

README.md
=> Update readme link for spec

.github/workflows/test.yaml, src/schemas/block.yaml
Making td optional until #250 is resolved.
=> Make td optional field on block

src/engine/authentication.md
closes #184. @rauljordan is this what you had in mind?
=> Clarify meaning of client in auth

package.json, schema.graphqls, scripts/graphql-validate.js, scripts/graphql.js
Add support for generating the GraphQL Schema, which
is the common schema form used for GraphQL libraries.
=> Add GraphQL Schema

src/eth/sign.yaml, src/eth/submit.yaml, src/schemas/transaction.yaml
=> Use generic tx for `eth_sign` + `eth_sendtransaction` and add `from` field

src/engine/experimental/blob-extension.md
=> Add block value response to blob-extension spec

src/engine/experimental/blob-extension.md
Fix broken link in `blob-extension.md`
=> fix(blob): broken links

README.md, docs/making-changes.md, src/engine/paris.md
=> Fix: typos

src/engine/common.md
=> Fix `exchangeCapabilities` examples

scripts/build.js
Addresses https://github.com/ethereum/execution-apis/pull/435#discussion_r1255913422
=> directly use `merger` function to merge schemas combined using allOf

src/engine/cancun.md, src/engine/experimental/eip6110.md, src/engine/openrpc/schemas/payload.yaml
Address https://github.com/ethereum/EIPs/pull/7354
=> Rename "data gas" to "blob gas"

src/engine/README.md
* Add Cancun to the list of spec documents
* Remove a note about schema to be created as it was created already
* Add https://hackmd.io/@danielrachi/engine_api to the list of references, many thanks to @danielrachi for the writeup!
=> engine: update README.md

src/schemas/filter.yaml
Some issues were surfaced by Felix's new tests in #513. This PR will resolve the filter issues.
=> schemas/filter: fixup some bugs in null filter topics and address

src/schemas/receipt.yaml
`name` isn't valid json-schema. it should be `title`.
=> Update receipt.yaml to title instead of name

src/engine/prague.md
`DepositRequestV1` links to its relevant EIP (EIP-6110). This PR links `WithdrawalRequestV1` to its relevant EIP (EIP-7002).
=> docs: link to eip-7002 in prague engine spec

src/engine/openrpc/methods/payload.yaml, src/engine/openrpc/schemas/payload.yaml, src/engine/prague.md
Engine API specification for:
* https://github.com/ethereum/EIPs/pull/8625
This PR:
* Adds `ConsolidationRequestV1` struct
* Adds `consolidationRequests` to `newPayloadV4` and `getPayloadBodiesBy{Hash|Range}V2`
* Updates the schema
=> engine: Add EL triggered consolidations

src/eth/block.yaml, src/eth/state.yaml, src/schemas/block.yaml
Minor fixes to `eth` method examples addressing the following issues:
Fixes #580 
Fixes #581
=> Minor fixes to `eth` methods

src/eth/block.yaml, src/schemas/block.yaml
This reverts commit 7c9772f95c2472ccfc6f6128dc2e1b568284a2da.
=> Revert "EIP-7742 - Add target_blobs_per_block to Block schema (#601)"

src/eth/fee_market.yaml, tests/eth_getLogs/topic-exact-match.io
This pull request contains changes to improve clarity, correctness and structure.
=> fix: typos in documentation files

README.md
=> readme: fix playground link

src/eth/transaction.yaml
closes this https://github.com/ethereum/execution-apis/issues/635
=> convert chainId to hex in transaction example
